// <auto-generated />
using System;
using System.Collections.Generic;
using EtalDeJeux.Api.Data;
using EtalDeJeux.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EtalDeJeux.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251014120000_AddEmailLogs")]
    partial class AddEmailLogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EtalDeJeux.Api.Models.Designer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_designers");

                    b.ToTable("designers", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Mechanic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_mechanics");

                    b.ToTable("mechanics", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountDiscount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_discount");

                    b.Property<decimal>("AmountShipping")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_shipping");

                    b.Property<decimal>("AmountSubtotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_subtotal");

                    b.Property<decimal>("AmountTax")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_tax");

                    b.Property<decimal>("AmountTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_total");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_orders_status_created_at");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.OrderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_order_events");

                    b.ToTable("order_events", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("MessageId")
                        .HasColumnType("text")
                        .HasColumnName("message_id");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status")
                        .HasDefaultValue("sent");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_email");

                    b.HasKey("Id")
                        .HasName("pk_email_logs");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_email_logs_order");

                    b.HasIndex("ToEmail")
                        .HasDatabaseName("idx_email_logs_to");

                    b.ToTable("email_logs", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrlSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("image_url_snapshot");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_snapshot");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<Guid?>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPaymentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_payment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payments_order_id");

                    b.HasIndex("Provider", "ProviderPaymentId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_provider_provider_payment_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_payments_status_created_at");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.PaymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_payment_events");

                    b.ToTable("payment_events", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<decimal?>("Complexity")
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("complexity");

                    b.Property<List<ProductContentItem>>("Contents")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contents");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<List<string>>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("images");

                    b.PrimitiveCollection<List<string>>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("languages");

                    b.Property<short?>("MaxPlayers")
                        .HasColumnType("smallint")
                        .HasColumnName("max_players");

                    b.Property<short?>("MinAge")
                        .HasColumnType("smallint")
                        .HasColumnName("min_age");

                    b.Property<short?>("MinPlayers")
                        .HasColumnType("smallint")
                        .HasColumnName("min_players");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_product_id");

                    b.Property<short?>("PlaytimeMax")
                        .HasColumnType("smallint")
                        .HasColumnName("playtime_max");

                    b.Property<short?>("PlaytimeMin")
                        .HasColumnType("smallint")
                        .HasColumnName("playtime_min");

                    b.Property<short?>("ReleaseYear")
                        .HasColumnType("smallint")
                        .HasColumnName("release_year");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("ParentProductId")
                        .HasDatabaseName("ix_products_parent_product_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_products_slug");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductDesigner", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("DesignerId")
                        .HasColumnType("bigint")
                        .HasColumnName("designer_id");

                    b.HasKey("ProductId", "DesignerId")
                        .HasName("pk_product_designers");

                    b.HasIndex("DesignerId")
                        .HasDatabaseName("ix_product_designers_designer_id");

                    b.ToTable("product_designers", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<string>("Kind")
                        .HasMaxLength(40)
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_product_files");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_files_product_id");

                    b.ToTable("product_files", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductMechanic", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("MechanicId")
                        .HasColumnType("bigint")
                        .HasColumnName("mechanic_id");

                    b.HasKey("ProductId", "MechanicId")
                        .HasName("pk_product_mechanics");

                    b.HasIndex("MechanicId")
                        .HasDatabaseName("ix_product_mechanics_mechanic_id");

                    b.ToTable("product_mechanics", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductPublisher", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("PublisherId")
                        .HasColumnType("bigint")
                        .HasColumnName("publisher_id");

                    b.HasKey("ProductId", "PublisherId")
                        .HasName("pk_product_publishers");

                    b.HasIndex("PublisherId")
                        .HasDatabaseName("ix_product_publishers_publisher_id");

                    b.ToTable("product_publishers", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Publisher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_publishers");

                    b.ToTable("publishers", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_reservations_status_expires_at");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ReservationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.HasKey("Id")
                        .HasName("pk_reservation_items");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_reservation_items_reservation_id");

                    b.HasIndex("SkuId")
                        .HasDatabaseName("ix_reservation_items_sku_id");

                    b.ToTable("reservation_items", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("ReservedQty")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_qty");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku_code");

                    b.Property<int>("SoldQty")
                        .HasColumnType("integer")
                        .HasColumnName("sold_qty");

                    b.Property<int>("StockTotal")
                        .HasColumnType("integer")
                        .HasColumnName("stock_total");

                    b.HasKey("Id")
                        .HasName("pk_skus");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_skus_product_id");

                    b.HasIndex("SkuCode")
                        .IsUnique()
                        .HasDatabaseName("ix_skus_sku_code");

                    b.ToTable("skus", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("InitialAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("initial_amount");

                    b.Property<string>("IssuedToEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issued_to_email");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("RemainingAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("remaining_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_vouchers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_vouchers_code");

                    b.ToTable("vouchers", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.VoucherRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountUsed")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_used");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("RedeemedByOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("redeemed_by_order_id");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.HasKey("Id")
                        .HasName("pk_voucher_redemptions");

                    b.ToTable("voucher_redemptions", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.WebhookEventRaw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_webhook_events_raw");

                    b.ToTable("webhook_events_raw", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.EmailLog", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_email_logs_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.OrderItem", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Payment", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Product", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Product", "ParentProduct")
                        .WithMany("Children")
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_products_products_parent_product_id");

                    b.Navigation("ParentProduct");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductDesigner", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Designer", "Designer")
                        .WithMany("ProductDesigners")
                        .HasForeignKey("DesignerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_designers_designers_designer_id");

                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("ProductDesigners")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_designers_products_product_id");

                    b.Navigation("Designer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductFile", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("Files")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_files_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductMechanic", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Mechanic", "Mechanic")
                        .WithMany("ProductMechanics")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_mechanics_mechanics_mechanic_id");

                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("ProductMechanics")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_mechanics_products_product_id");

                    b.Navigation("Mechanic");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductPublisher", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("ProductPublishers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_publishers_products_product_id");

                    b.HasOne("EtalDeJeux.Api.Models.Publisher", "Publisher")
                        .WithMany("ProductPublishers")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_publishers_publishers_publisher_id");

                    b.Navigation("Product");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ReservationItem", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Reservation", "Reservation")
                        .WithMany("Items")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_items_reservations_reservation_id");

                    b.HasOne("EtalDeJeux.Api.Models.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_items_skus_sku_id");

                    b.Navigation("Reservation");

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Sku", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("Skus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skus_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Designer", b =>
                {
                    b.Navigation("ProductDesigners");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Mechanic", b =>
                {
                    b.Navigation("ProductMechanics");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Product", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Files");

                    b.Navigation("ProductDesigners");

                    b.Navigation("ProductMechanics");

                    b.Navigation("ProductPublishers");

                    b.Navigation("Skus");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Publisher", b =>
                {
                    b.Navigation("ProductPublishers");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Reservation", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
