// <auto-generated />
using System;
using System.Collections.Generic;
using EtalDeJeux.Api.Data;
using EtalDeJeux.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EtalDeJeux.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250101000000_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Npgsql:Enum:file_kind", new[] { "pdf", "image", "zip", "rules", "scenario" })
                .HasAnnotation("Npgsql:Enum:product_type", new[] { "board_game", "expansion", "rpg", "accessory", "digital" });

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EtalDeJeux.Api.Models.Designer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Designers");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Mechanic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("Mechanics");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal?>("Complexity")
                        .HasColumnType("numeric(2,1)");

                    b.PrimitiveCollection<List<ProductContentItem>>("Contents")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<List<string>>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<short?>("MaxPlayers")
                        .HasColumnType("smallint");

                    b.Property<short?>("MinAge")
                        .HasColumnType("smallint");

                    b.Property<short?>("MinPlayers")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("ParentProductId")
                        .HasColumnType("uuid");

                    b.Property<short?>("PlaytimeMax")
                        .HasColumnType("smallint");

                    b.Property<short?>("PlaytimeMin")
                        .HasColumnType("smallint");

                    b.Property<short?>("ReleaseYear")
                        .HasColumnType("smallint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<ProductType>("Type")
                        .HasColumnType("product_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ParentProductId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductDesigner", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<long>("DesignerId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId", "DesignerId");

                    b.HasIndex("DesignerId");

                    b.ToTable("ProductDesigners");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<FileKind>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("file_kind")
                        .HasDefaultValue(FileKind.Pdf);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFiles");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductMechanic", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<long>("MechanicId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId", "MechanicId");

                    b.HasIndex("MechanicId");

                    b.ToTable("ProductMechanics");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductPublisher", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<long>("PublisherId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId", "PublisherId");

                    b.HasIndex("PublisherId");

                    b.ToTable("ProductPublishers");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Publisher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SkuCode")
                        .IsUnique();

                    b.ToTable("Skus");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Product", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Product", "ParentProduct")
                        .WithMany("Children")
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentProduct");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductDesigner", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Designer", "Designer")
                        .WithMany("ProductDesigners")
                        .HasForeignKey("DesignerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("ProductDesigners")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Designer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductFile", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("Files")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductMechanic", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Mechanic", "Mechanic")
                        .WithMany("ProductMechanics")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("ProductMechanics")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mechanic");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductPublisher", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("ProductPublishers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtalDeJeux.Api.Models.Publisher", "Publisher")
                        .WithMany("ProductPublishers")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Sku", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("Skus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Designer", b =>
                {
                    b.Navigation("ProductDesigners");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Mechanic", b =>
                {
                    b.Navigation("ProductMechanics");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Product", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Files");

                    b.Navigation("ProductDesigners");

                    b.Navigation("ProductMechanics");

                    b.Navigation("ProductPublishers");

                    b.Navigation("Skus");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Publisher", b =>
                {
                    b.Navigation("ProductPublishers");
                });
#pragma warning restore 612, 618
        }
    }
}
