// <auto-generated />
using System;
using System.Collections.Generic;
using EtalDeJeux.Api.Data;
using EtalDeJeux.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EtalDeJeux.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EtalDeJeux.Api.Models.Designer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_designers");

                    b.ToTable("designers", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Mechanic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_mechanics");

                    b.ToTable("mechanics", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<decimal?>("Complexity")
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("complexity");

                    b.Property<List<ProductContentItem>>("Contents")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contents");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<List<string>>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("images");

                    b.PrimitiveCollection<List<string>>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("languages");

                    b.Property<short?>("MaxPlayers")
                        .HasColumnType("smallint")
                        .HasColumnName("max_players");

                    b.Property<short?>("MinAge")
                        .HasColumnType("smallint")
                        .HasColumnName("min_age");

                    b.Property<short?>("MinPlayers")
                        .HasColumnType("smallint")
                        .HasColumnName("min_players");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_product_id");

                    b.Property<short?>("PlaytimeMax")
                        .HasColumnType("smallint")
                        .HasColumnName("playtime_max");

                    b.Property<short?>("PlaytimeMin")
                        .HasColumnType("smallint")
                        .HasColumnName("playtime_min");

                    b.Property<short?>("ReleaseYear")
                        .HasColumnType("smallint")
                        .HasColumnName("release_year");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<string>("Type")
                        .HasMaxLength(40)
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("ParentProductId")
                        .HasDatabaseName("ix_products_parent_product_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_products_slug");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductDesigner", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("DesignerId")
                        .HasColumnType("bigint")
                        .HasColumnName("designer_id");

                    b.HasKey("ProductId", "DesignerId")
                        .HasName("pk_product_designers");

                    b.HasIndex("DesignerId")
                        .HasDatabaseName("ix_product_designers_designer_id");

                    b.ToTable("product_designers", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<string>("Kind")
                        .HasMaxLength(40)
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_product_files");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_files_product_id");

                    b.ToTable("product_files", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductMechanic", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("MechanicId")
                        .HasColumnType("bigint")
                        .HasColumnName("mechanic_id");

                    b.HasKey("ProductId", "MechanicId")
                        .HasName("pk_product_mechanics");

                    b.HasIndex("MechanicId")
                        .HasDatabaseName("ix_product_mechanics_mechanic_id");

                    b.ToTable("product_mechanics", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductPublisher", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("PublisherId")
                        .HasColumnType("bigint")
                        .HasColumnName("publisher_id");

                    b.HasKey("ProductId", "PublisherId")
                        .HasName("pk_product_publishers");

                    b.HasIndex("PublisherId")
                        .HasDatabaseName("ix_product_publishers_publisher_id");

                    b.ToTable("product_publishers", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Publisher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_publishers");

                    b.ToTable("publishers", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku_code");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("pk_skus");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_skus_product_id");

                    b.HasIndex("SkuCode")
                        .IsUnique()
                        .HasDatabaseName("ix_skus_sku_code");

                    b.ToTable("skus", (string)null);
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Product", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Product", "ParentProduct")
                        .WithMany("Children")
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_products_products_parent_product_id");

                    b.Navigation("ParentProduct");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductDesigner", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Designer", "Designer")
                        .WithMany("ProductDesigners")
                        .HasForeignKey("DesignerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_designers_designers_designer_id");

                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("ProductDesigners")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_designers_products_product_id");

                    b.Navigation("Designer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductFile", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("Files")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_files_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductMechanic", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Mechanic", "Mechanic")
                        .WithMany("ProductMechanics")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_mechanics_mechanics_mechanic_id");

                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("ProductMechanics")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_mechanics_products_product_id");

                    b.Navigation("Mechanic");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.ProductPublisher", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("ProductPublishers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_publishers_products_product_id");

                    b.HasOne("EtalDeJeux.Api.Models.Publisher", "Publisher")
                        .WithMany("ProductPublishers")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_publishers_publishers_publisher_id");

                    b.Navigation("Product");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Sku", b =>
                {
                    b.HasOne("EtalDeJeux.Api.Models.Product", "Product")
                        .WithMany("Skus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skus_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Designer", b =>
                {
                    b.Navigation("ProductDesigners");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Mechanic", b =>
                {
                    b.Navigation("ProductMechanics");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Product", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Files");

                    b.Navigation("ProductDesigners");

                    b.Navigation("ProductMechanics");

                    b.Navigation("ProductPublishers");

                    b.Navigation("Skus");
                });

            modelBuilder.Entity("EtalDeJeux.Api.Models.Publisher", b =>
                {
                    b.Navigation("ProductPublishers");
                });
#pragma warning restore 612, 618
        }
    }
}
